version: '3.8'

services:
  client_server:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8000:8000"

  barista_server:
    build:
      context: .
      dockerfile: Dockerfile.barista
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client_server
      - barista_server
